applicationWeb/Models/Avion.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace applicationWeb.Models
{
    public class Avion
    {
       
        [Key]
        
        [DisplayName("Numero Avion")]
        [Range(1,11)]
        public int Numavion { get; set; }
        
        [DisplayName("Nom Avion")]

        [MaxLength(20)]
        public string Nomavion { get; set; }

        
        public int Capacite { get; set; }

        [MaxLength(20)]
        public string Localisation { get; set; }
    }
}

applicationWeb/Controllers/AvionController.cs
using applicationWeb.Data;
using applicationWeb.Models;
using applicationWeb.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace applicationWeb.Controllers
{
    public class AvionController : Controller
    {
        private readonly IAvionRepository _avionRepo;
        public AvionController(IAvionRepository db)
        {
            _avionRepo = db;
        }
        public IActionResult Index()
        {
            List<Avion> objAvionList = _avionRepo.GetAll().ToList();

            return View(objAvionList);
        }

        public IActionResult Create()
        {
            return View();
        }





        [HttpPost]
        public IActionResult Create(Avion obj)
        {
            //_db.Database.OpenConnection();
            try
            {

                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _avionRepo.Add(obj);
                _avionRepo.Save();
                    TempData["success"] = "Un Avion a été ajouté avec succès";
                
               
            }
            finally
            {
                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
               // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int? id)
        {
            
            if(id == null || id== 0) {
            
                return NotFound();
            
            }

            Avion? avionFromDb = _avionRepo.Get(u=>u.Numavion==id);

            if(avionFromDb == null)
            {
                return NotFound();
            }
            
            return View(avionFromDb);
        }





        [HttpPost]
        public IActionResult Edit(Avion obj)
        {
            //_db.Database.OpenConnection();
            try
            {

                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _avionRepo.Update(obj);
                _avionRepo.Save();
                TempData["success"] = "Un Avion a été modifie avec succès";

            }
            finally
            {
                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
               // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {

                return NotFound();

            }

            Avion? avionFromDb = _avionRepo.Get(u => u.Numavion == id);

            if (avionFromDb == null)
            {
                return NotFound();
            }

            return View(avionFromDb);
        }





        [HttpPost,ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
          //  _db.Database.OpenConnection();

            Avion? obj = _avionRepo.Get(u => u.Numavion == id);

            if (obj == null)
            {
                return NotFound(id);
            }

           
            try
            {

               // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _avionRepo.Remove(obj);
                _avionRepo.Save();
                TempData["success"] = "Un Avion a été suprime avec succès";

            }
            finally
            {
               // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
               // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }
    }


}

applicationWeb/Views/Avion/Create.cshtml
@model Avion



<form asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ajouter Un Avion</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numavion" class="p-0"></label>
            <input asp-for="Numavion"  class="form-control"/>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nomavion" class="p-0"></label>
            <input asp-for="Nomavion" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Capacite" class="p-0"></label>
            <input asp-for="Capacite" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Localisation" class="p-0"></label>
            <input asp-for="Localisation" class="form-control" />

        </div>

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Ajouter</button>
            </div>
            <div class="col-6">
                <a asp-controller="Avion" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>
        
        


    </div>





</form>

applicationWeb/Views/Avion/Delete.cshtml
@model Avion




<form method="post">
    <input asp-for="Numavion" hidden /> 
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Suprimer  Un Avion</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numavion" class="p-0"></label>
            <input asp-for="Numavion" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nomavion" class="p-0"></label>
            <input asp-for="Nomavion" disabled class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Capacite" class="p-0"></label>
            <input asp-for="Capacite" disabled d class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Localisation" class="p-0"></label>
            <input asp-for="Localisation" disabled class="form-control" />

        </div>

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger form-control">Suprimer</button>
            </div>
            <div class="col-6">
                <a asp-controller="Avion" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Avion/Edit.cshtml
@model Avion
<h1>Edit</h1>



<form method="post">
     <input asp-for="Numavion" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Modifier Un Avion</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numavion" class="p-0"></label>
            <input asp-for="Numavion" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nomavion" class="p-0"></label>
            <input asp-for="Nomavion" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Capacite" class="p-0"></label>
            <input asp-for="Capacite" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Localisation" class="p-0"></label>
            <input asp-for="Localisation" class="form-control" />

        </div>

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Modifier</button>
            </div>
            <div class="col-6">
                <a asp-controller="Avion" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Avion/Index.cshtml
@model List<Avion>
@if (TempData["success"] != null)
{
    <div id="successMessage" class="alert alert-success" role="alert">
        <h2>@TempData["success"]</h2>
    </div>
}

<div class="row pt-4 pb-3">
    <div class="col-6">
        <h2 class="text-primary">Liste Des Avions</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Avion" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Ajouter Un Avion
        </a>
    </div>
    <div class="row pt-4 pb-3">
       
        <div class="col-12 mb-3">
            <input type="text" id="filtreNumAvion" placeholder="Entrer le numéro d'avion" class="form-control" style="display: inline-block; width: auto;" />
            <button id="btnFiltrer" class="btn btn-primary">Filtrer</button>
        </div>

      
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Numero Avion</th>
            <th>Nom Avion</th>
            <th>Capacite</th>
            <th>Localisation</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            
            
                <tr>
                    <td>@obj.Numavion</td>
                    <td>@obj.Nomavion</td>
                    <td>@obj.Capacite</td>
                    <td>@obj.Localisation</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Avion" asp-action="Edit" asp-route-id="@obj.Numavion" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil"></i>Modifier
                            </a>
                            <a asp-controller="Avion" asp-action="Delete" asp-route-id="@obj.Numavion" class="btn btn-danger mx-2">
                                <i class="bi bi-trash"></i>Supprimer
                            </a>
                        </div>
                    </td>
                </tr>
            
        }
    </tbody>
</table>


@section scripts { 
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const btnFiltrer = document.getElementById('btnFiltrer');
        btnFiltrer.addEventListener('click', function () {
            const term = document.getElementById('filtreNumAvion').value.trim(); 
            const rows = document.querySelectorAll('table tbody tr');

            rows.forEach(row => {
                const numAvion = row.querySelector('td:first-child').textContent.trim(); 
                if (numAvion === term) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    });
        $(document).ready(function () {

            if ($('#successMessage').length) {
                setTimeout(function () {
                    $('#successMessage').fadeOut();
                }, 3000);
            }
        });
</script>
}

</section>