applicationWeb/Models/Vol.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace applicationWeb.Models
{
    public class Vol
    {
        [Key]

        [DisplayName("Numero Vol")]
        [Range(1, 11)]
        public string Numvol { get; set; }

        

        public int Numpilote { get; set; }
        [ForeignKey("Numpilote")]
        public Pilote Pilote { get; set; }
       
        
        

        public int Numavion { get; set; }
        [ForeignKey("Numavion")]
        public Avion Avion { get; set; }


        [DisplayName("Ville  Depart")]

        public string Villedep { get; set; }

        [DisplayName("Ville Arrive")]

        public string Villearr { get; set; }
       
        [DisplayName("Heure  Depart")]

        public string Heuredep { get; set; }

        [DisplayName("Heure Arrive")]

        public string Heurearr { get; set; }




    }
}

applicationWeb/Controllers/VolController.cs
using applicationWeb.Models;
using applicationWeb.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace applicationWeb.Controllers
{
    public class VolController : Controller
    {
        private readonly IVolRepository _volRepo;
        public VolController(IVolRepository db)
        {
            _volRepo = db;
        }
        public IActionResult Index()
        {
            List<Vol> objVolList = _volRepo.GetAll().ToList();
           

            return View(objVolList);
        }

        public IActionResult Create()
        {
            
            IEnumerable<SelectListItem> PiloteList = 
                                                     
                _volRepo.GetPiloteList().Select(p => new SelectListItem
                {
                    Value = p.Numpilote.ToString(),
                    Text = p.Numpilote.ToString() 
                });

            
            IEnumerable<SelectListItem> AvionList = 
                                                    
                _volRepo.GetAvionList().Select(a => new SelectListItem
                {
                    Value = a.Numavion.ToString(),
                    Text = a.Numavion.ToString() 
                });

           
            ViewBag.PiloteList = PiloteList;
            ViewBag.AvionList = AvionList;

            return View();
        }





        [HttpPost]
        public IActionResult Create(Vol obj)
        {
            //_db.Database.OpenConnection();
            try
            {

                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _volRepo.Add(obj);
                _volRepo.Save();
                TempData["success"] = "Un Vol a été ajouté avec succès";


            }
            finally
            {
                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
                // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }


        public IActionResult Edit(string? id)
        {
            if (id == null || id == "")
            {
                return NotFound();
            }

            Vol? volFromDb = _volRepo.Get(u => u.Numvol == id);

            if (volFromDb == null)
            {
                return NotFound();
            }

            
            IEnumerable<SelectListItem> PiloteList = _volRepo.GetPiloteList().Select(p => new SelectListItem
            {
                Value = p.Numpilote.ToString(),
                Text = p.Numpilote.ToString()
            });

            // Récupérer la liste des avions
            IEnumerable<SelectListItem> AvionList = _volRepo.GetAvionList().Select(a => new SelectListItem
            {
                Value = a.Numavion.ToString(),
                Text = a.Numavion.ToString()
            });

            
            ViewBag.PiloteList = PiloteList;
            ViewBag.AvionList = AvionList;

            return View(volFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Vol obj)
        {
            try
            {
                _volRepo.Update(obj);
                _volRepo.Save();
                TempData["success"] = "Un Vol a été modifié avec succès";
            }
            catch (Exception ex)
            {
                // Gérer les erreurs, par exemple, en ajoutant ModelState.AddModelError
                TempData["error"] = "Une erreur s'est produite lors de la modification du vol.";
                return View(obj);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(string? id)
        {

            if (id == null || id == "")
            {

                return NotFound();

            }

            Vol? volFromDb = _volRepo.Get(u => u.Numvol == id);

            if (volFromDb == null)
            {
                return NotFound();
            }

            return View(volFromDb);
        }





        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(string? id)
        {
            //  _db.Database.OpenConnection();

            Vol? obj = _volRepo.Get(u => u.Numvol == id);

            if (obj == null)
            {
                return NotFound(id);
            }


            try
            {

                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _volRepo.Remove(obj);
                _volRepo.Save();
                TempData["success"] = "Un Vol a été suprime avec succès";

            }
            finally
            {
                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
                // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }
    }
}

applicationWeb/Views/Vol/Create.cshtml
@model Vol



<form asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ajouter Un Vol</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numvol" class="p-0"></label>
            <input asp-for="Numvol" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <div class="form-group">
                <label asp-for="Numpilote" class="control-label"></label>
                <select asp-for="Numpilote" class="form-control" asp-items="ViewBag.PiloteList"></select>
                <span asp-validation-for="Numpilote" class="text-danger"></span>
            </div>
           

        </div>
        <div class="mb-3 row p-1">
            <div class="form-group">
                <label asp-for="Numavion" class="control-label"></label>
                <select asp-for="Numavion" class="form-control" asp-items="ViewBag.AvionList"></select>
                <span asp-validation-for="Numavion" class="text-danger"></span>
            </div>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villedep" class="p-0"></label>
            <input asp-for="Villedep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villearr" class="p-0"></label>
            <input asp-for="Villearr" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heuredep" class="p-0"></label>
            <input asp-for="Heuredep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heurearr" class="p-0"></label>
            <input asp-for="Heurearr" class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Ajouter</button>
            </div>
            <div class="col-6">
                <a asp-controller="Vol" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>
        
        


    </div>





</form>

applicationWeb/Views/Vol/Delete.cshtml
@model Vol




<form method="post">
    <input asp-for="Numvol" hidden /> 
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Suprimer  Un Vol</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numvol" class="p-0"></label>
            <input asp-for="Numvol" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numpilote" class="p-0"></label>
            <input asp-for="Numpilote" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numavion" class="p-0"></label>
            <input asp-for="Numavion" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villedep" class="p-0"></label>
            <input asp-for="Villedep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villearr" class="p-0"></label>
            <input asp-for="Villearr" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heuredep" class="p-0"></label>
            <input asp-for="Heuredep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heurearr" class="p-0"></label>
            <input asp-for="Heurearr" class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger form-control">Suprimer</button>
            </div>
            <div class="col-6">
                <a asp-controller="Vol" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Vol/Edit.cshtml
@model Vol
<h1>Edit</h1>



<form method="post">
     <input asp-for="Numvol" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Modifier Un Vol</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numvol" class="p-0"></label>
            <input asp-for="Numvol" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <div class="form-group">
                <label asp-for="Numpilote" class="control-label"></label>
                <select asp-for="Numpilote" class="form-control" asp-items="ViewBag.PiloteList"></select>
                <span asp-validation-for="Numpilote" class="text-danger"></span>
            </div>

        </div>
        <div class="mb-3 row p-1">
            <div class="form-group">
                <label asp-for="Numavion" class="control-label"></label>
                <select asp-for="Numavion" class="form-control" asp-items="ViewBag.AvionList"></select>
                <span asp-validation-for="Numavion" class="text-danger"></span>
            </div>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villedep" class="p-0"></label>
            <input asp-for="Villedep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Villearr" class="p-0"></label>
            <input asp-for="Villearr" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heuredep" class="p-0"></label>
            <input asp-for="Heuredep" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Heurearr" class="p-0"></label>
            <input asp-for="Heurearr" class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Modifier</button>
            </div>
            <div class="col-6">
                <a asp-controller="Vol" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Vol/Index.cshtml
@model List<Vol>


@if(TempData["success"] != null)
{
    <div id="successMessage" class="alert alert-success" role="alert">
        <h2>@TempData["success"]</h2>
    </div>
}
 <div class="row pt-4 pb-3">

        <div class="col-6">
            <h2 class="text-primary">
                Liste Des Vols
            </h2>

        </div>
        <div class="col-6  text-end">
            <a asp-controller="Vol"  asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Ajouter Un Vol
            </a>

        </div>
        <div class="row pt-4 pb-3">
            <div class="col-6 mb-3">
                <input type="text" id="filtreNumeroAvion" placeholder="Entrer le Numero d'avion" class="form-control" style="display: inline-block; width: auto;" />
                <button id="btnFiltrere" class="btn btn-primary">Filtrer</button>
            </div>
            <div class="col-6 mb-3">
                <input type="text" id="filtreNumeroPilote" placeholder="Entrer le Numero  Pilote" class="form-control" style="display: inline-block; width: auto;" />
                <button id="btnFiltrer" class="btn btn-primary">Filtrer</button>
            </div>
        </div>
    



  </div>



<table class="table table-bordered table-striped">
    
    <thead>
    <tr>
        <th>
            Numero Vol



        </th>
        <th>

             Numero Pilote


        </th>
        <th>
            Numero Avion



        </th>
            <th>
                Ville Depart



            </th>
            <th>
                Ville Arrivée



            </th>
            <th>
               Heure Depart



            </th>
            <th>
                Heure Arrivée



            </th>
        
        <th></th>





    </tr>
    </thead>

    <tbody>
        @foreach(var obj in Model){
        <tr>
            <td>@obj.Numvol</td>
            
            <td>@obj.Numpilote</td>
            <td>@obj.Numavion</td>
            <td>@obj.Villedep</td>
            <td>@obj.Villearr</td>
            <td>@obj.Heuredep</td>
            <td>@obj.Heurearr</td>
            
           
            <td>
                <div class="w-75 btn-group" role="group">
                    <a asp-controller="Vol" asp-action="Edit" asp-route-id="@obj.Numvol" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil"></i>Modifier
                    </a>
                        <a asp-controller="Vol" asp-action="Delete" asp-route-id="@obj.Numvol" class="btn btn-danger mx-2">
                            <i class="bi bi-trash"></i>Suprimer
                        </a>

                </div>
            </td>
        
        
        
        </tr>

        }


    </tbody>


</table>


@section scripts {

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const btnFiltrer = document.getElementById('btnFiltrere');
            btnFiltrer.addEventListener('click', function () {
                const term = document.getElementById('filtreNumeroAvion').value.trim();
                const rows = document.querySelectorAll('table tbody tr');

                rows.forEach(row => {
                    const adressePilote = row.querySelector('td:nth-child(3)').textContent.trim();
                    if (adressePilote === term) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        });
        document.addEventListener("DOMContentLoaded", function () {
            const btnFiltrer = document.getElementById('btnFiltrer');
            btnFiltrer.addEventListener('click', function () {
                const term = document.getElementById('filtreNumeroPilote').value.trim();
                const rows = document.querySelectorAll('table tbody tr');

                rows.forEach(row => {
                    const adressePilote = row.querySelector('td:nth-child(2)').textContent.trim();
                    if (adressePilote === term) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        });

        $(document).ready(function () {

            if ($('#successMessage').length) {
                setTimeout(function () {
                    $('#successMessage').fadeOut();
                }, 3000);
            }
        });
    </script>
}

</section>