applicationWeb/Models/Pilote.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace applicationWeb.Models
{
    public class Pilote
    {

        [Key]

        [DisplayName("Numero Pilote")]
        [Range(1, 11)]
        public int Numpilote { get; set; }

        [DisplayName("Nom Pilote")]

        [MaxLength(20)]
        public string Nompilote { get; set; }


        public string Adresse { get; set; }

        

    }
}

applicationWeb/Controllers/PiloteController.cs
using applicationWeb.Models;
using applicationWeb.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace applicationWeb.Controllers
{
    public class PiloteController : Controller
    {
        private readonly IPiloteRepository _piloteRepo;
        public PiloteController(IPiloteRepository db)
        {
            _piloteRepo = db;
        }
        public IActionResult Index()
        {
            List<Pilote> objPiloteList = _piloteRepo.GetAll().ToList();

            return View(objPiloteList);
        }

        public IActionResult Create()
        {
            return View();
        }





        [HttpPost]
        public IActionResult Create(Pilote obj)
        {
            //_db.Database.OpenConnection();
            try
            {

                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _piloteRepo.Add(obj);
                _piloteRepo.Save();
                TempData["success"] = "Un Pilote a été ajouté avec succès";


            }
            finally
            {
                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
                // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int? id)
        {

            if (id == null || id == 0)
            {

                return NotFound();

            }

            Pilote? piloteFromDb = _piloteRepo.Get(u => u.Numpilote == id);

            if (piloteFromDb == null)
            {
                return NotFound();
            }

            return View(piloteFromDb);
        }





        [HttpPost]
        public IActionResult Edit(Pilote obj)
        {
            //_db.Database.OpenConnection();
            try
            {

                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _piloteRepo.Update(obj);
                _piloteRepo.Save();
                TempData["success"] = "Un Pilote a été modifie avec succès";

            }
            finally
            {
                //_db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
                // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {

                return NotFound();

            }

            Pilote? piloteFromDb = _piloteRepo.Get(u => u.Numpilote == id);

            if (piloteFromDb == null)
            {
                return NotFound();
            }

            return View(piloteFromDb);
        }





        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            //  _db.Database.OpenConnection();

            Pilote? obj = _piloteRepo.Get(u => u.Numpilote == id);

            if (obj == null)
            {
                return NotFound(id);
            }


            try
            {

                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions ON;");
                _piloteRepo.Remove(obj);
                _piloteRepo.Save();
                TempData["success"] = "Un Pilote a été suprime avec succès";

            }
            finally
            {
                // _db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT avions OFF;");
                // _db.Database.CloseConnection();
            }
            return RedirectToAction("Index");
        }
    }
}

applicationWeb/Views/Pilote/Create.cshtml
@model Pilote



<form asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ajouter Un Pilote</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numpilote" class="p-0"></label>
            <input asp-for="Numpilote"  class="form-control"/>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nompilote" class="p-0"></label>
            <input asp-for="Nompilote" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Adresse" class="p-0"></label>
            <input asp-for="Adresse" class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Ajouter</button>
            </div>
            <div class="col-6">
                <a asp-controller="Pilote" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>
        
        


    </div>





</form>

applicationWeb/Views/Pilote/Delete.cshtml
@model Pilote




<form method="post">
    <input asp-for="Numpilote" hidden /> 
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Suprimer  Un Pilote</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numpilote" class="p-0"></label>
            <input asp-for="Numpilote" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nompilote" class="p-0"></label>
            <input asp-for="Nompilote" disabled class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Adresse" class="p-0"></label>
            <input asp-for="Adresse" disabled d class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger form-control">Suprimer</button>
            </div>
            <div class="col-6">
                <a asp-controller="Pilote" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Pilote/Edit.cshtml
@model Pilote
<h1>Edit</h1>



<form method="post">
     <input asp-for="Numpilote" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Modifier Un Avion</h2>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Numpilote" class="p-0"></label>
            <input asp-for="Numpilote" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nompilote" class="p-0"></label>
            <input asp-for="Nompilote" class="form-control" />

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Adresse" class="p-0"></label>
            <input asp-for="Adresse" class="form-control" />

        </div>
        

        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Modifier</button>
            </div>
            <div class="col-6">
                <a asp-controller="Pilote" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Retour
                </a>

            </div>

        </div>




    </div>





</form>

applicationWeb/Views/Pilote/Index.cshtml
@model List<Pilote>

@if (TempData["success"] != null)
{
    <div id="successMessage" class="alert alert-success" role="alert">
        <h2>@TempData["success"]</h2>
    </div>
}

<div class="row pt-4 pb-3">
    <div class="col-6">
        <h2 class="text-primary">Liste Des Pilotes</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Pilote" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Ajouter Un Pilote
        </a>
    </div>
</div>

<div class="row pt-4 pb-3">
    <div class="col-12 mb-3">
        <input type="text" id="filtreAdressePilote" placeholder="Entrer l'adresse du pilote" class="form-control" style="display: inline-block; width: auto;" />
        <button id="btnFiltrer" class="btn btn-primary">Filtrer</button>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Numero Pilote</th>
            <th>Nom Pilote</th>
            <th>Adresse</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Numpilote</td>
                <td>@obj.Nompilote</td>
                <td>@obj.Adresse</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Pilote" asp-action="Edit" asp-route-id="@obj.Numpilote" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil"></i>Modifier
                        </a>
                        <a asp-controller="Pilote" asp-action="Delete" asp-route-id="@obj.Numpilote" class="btn btn-danger mx-2">
                            <i class="bi bi-trash"></i>Supprimer
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts { 

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const btnFiltrer = document.getElementById('btnFiltrer');
            btnFiltrer.addEventListener('click', function () {
                const term = document.getElementById('filtreAdressePilote').value.trim();
                const rows = document.querySelectorAll('table tbody tr');

                rows.forEach(row => {
                    const adressePilote = row.querySelector('td:nth-child(3)').textContent.trim();
                    if (adressePilote === term) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        });

        $(document).ready(function () {
        
            if ($('#successMessage').length) {
                setTimeout(function () {
                    $('#successMessage').fadeOut();
                }, 3000); 
            }
        });
    </script>
}

</section>